# Generated by Django 2.1 on 2020-07-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200709_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_images/default3.jpg', upload_to='profile_pics'),
        ),
    ]
