# Generated by Django 2.2 on 2020-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_song',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
