# Generated by Django 3.0.8 on 2020-07-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'After'), (2, 'Before'), (3, 'Canceled')], default=2),
        ),
    ]
