# Generated by Django 3.0.8 on 2020-07-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.TextField(choices=[('ACTIVE', 'Active'), ('AFTER', 'After'), ('BEFORE', 'Before'), ('CANCELED', 'Canceled')], default='BEFORE'),
        ),
    ]
