# Generated by Django 3.0.8 on 2020-07-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200728_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsongs',
            name='event',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsongs',
            name='status',
            field=models.TextField(choices=[('ACTIVE', 'Active'), ('AFTER', 'After'), ('BEFORE', 'Before'), ('CANCELED', 'Canceled')], default='LISTED'),
        ),
    ]
