# Generated by Django 2.1 on 2020-07-09 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orgenizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party_Song_Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lyrics_url', models.CharField(max_length=400)),
                ('chords_url', models.CharField(max_length=400)),
                ('lyrics', models.TextField()),
                ('chords', models.TextField()),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karioker.Composers')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karioker.Performers')),
            ],
        ),
        migrations.CreateModel(
            name='SongWriters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='songs',
            name='songwriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karioker.SongWriters'),
        ),
        migrations.AddField(
            model_name='party_song_lists',
            name='Song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karioker.Songs'),
        ),
        migrations.AddField(
            model_name='party_song_lists',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karioker.Parties'),
        ),
    ]
