# Generated by Django 2.2 on 2020-07-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karioker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='alignment',
            field=models.CharField(default='right', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='language',
            field=models.CharField(default='Hebrew', max_length=400),
            preserve_default=False,
        ),
    ]
